apiVersion: apps/v1
kind: Deployment
metadata:
  name: k-test
spec:
  selector:
    matchLabels:
      app: k-test
  replicas: 2
  template:
    metadata:
      labels:
        app: k-test
    spec:
      containers:
      - name: k-test
        image: nanajanashia/argocd-app:1.2
        ports:
        - containerPort: 8080
